//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NybSys.MTBF.Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NavigationKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavigationKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NybSys.MTBF.Utility.Resources.NavigationKeys", typeof(NavigationKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityCenters.
        /// </summary>
        public static string ACTIVITY_CENTERS {
            get {
                return ResourceManager.GetString("ACTIVITY_CENTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildBudget.
        /// </summary>
        public static string BUILD_BUDGET {
            get {
                return ResourceManager.GetString("BUILD_BUDGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoA.
        /// </summary>
        public static string CHART_OF_ACCOUNTS {
            get {
                return ResourceManager.GetString("CHART_OF_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlItems.
        /// </summary>
        public static string CONTROL_ITEMS {
            get {
                return ResourceManager.GetString("CONTROL_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailItems.
        /// </summary>
        public static string DETAIL_ITEMS {
            get {
                return ResourceManager.GetString("DETAIL_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InflationRate.
        /// </summary>
        public static string INFLATION_RATE {
            get {
                return ResourceManager.GetString("INFLATION_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportingItems.
        /// </summary>
        public static string REPORTING_ITEMS {
            get {
                return ResourceManager.GetString("REPORTING_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResponsibilityCenters.
        /// </summary>
        public static string RESPONSIBILITY_CENTERS {
            get {
                return ResourceManager.GetString("RESPONSIBILITY_CENTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetCelling.
        /// </summary>
        public static string SET_CELLING {
            get {
                return ResourceManager.GetString("SET_CELLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskType.
        /// </summary>
        public static string TASK_TYPE {
            get {
                return ResourceManager.GetString("TASK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string UNIT_OF_MEASURE {
            get {
                return ResourceManager.GetString("UNIT_OF_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewBudget.
        /// </summary>
        public static string VIEW_BUDGET {
            get {
                return ResourceManager.GetString("VIEW_BUDGET", resourceCulture);
            }
        }
    }
}
