//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NybSys.MTBF.Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PermissionList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PermissionList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NybSys.MTBF.Utility.Resources.PermissionList", typeof(PermissionList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100402.
        /// </summary>
        public static string ACC_MAP_ADD {
            get {
                return ResourceManager.GetString("ACC_MAP_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100404.
        /// </summary>
        public static string ACC_MAP_DELETE {
            get {
                return ResourceManager.GetString("ACC_MAP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100401.
        /// </summary>
        public static string ACC_MAP_READ {
            get {
                return ResourceManager.GetString("ACC_MAP_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100403.
        /// </summary>
        public static string ACC_MAP_UPDATE {
            get {
                return ResourceManager.GetString("ACC_MAP_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101503.
        /// </summary>
        public static string BUDGET_APPR_EXPORT {
            get {
                return ResourceManager.GetString("BUDGET_APPR_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101504.
        /// </summary>
        public static string BUDGET_APPR_IMPORT {
            get {
                return ResourceManager.GetString("BUDGET_APPR_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101501.
        /// </summary>
        public static string BUDGET_APPR_READ {
            get {
                return ResourceManager.GetString("BUDGET_APPR_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101502.
        /// </summary>
        public static string BUDGET_APPR_SAVE {
            get {
                return ResourceManager.GetString("BUDGET_APPR_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101302.
        /// </summary>
        public static string BUDGET_CAP_ADD {
            get {
                return ResourceManager.GetString("BUDGET_CAP_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101304.
        /// </summary>
        public static string BUDGET_CAP_DELETE {
            get {
                return ResourceManager.GetString("BUDGET_CAP_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101305.
        /// </summary>
        public static string BUDGET_CAP_EXPORT {
            get {
                return ResourceManager.GetString("BUDGET_CAP_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101306.
        /// </summary>
        public static string BUDGET_CAP_IMPORT {
            get {
                return ResourceManager.GetString("BUDGET_CAP_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101301.
        /// </summary>
        public static string BUDGET_CAP_READ {
            get {
                return ResourceManager.GetString("BUDGET_CAP_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101303.
        /// </summary>
        public static string BUDGET_CAP_UPDATE {
            get {
                return ResourceManager.GetString("BUDGET_CAP_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101102.
        /// </summary>
        public static string BUDGET_REC_ADD {
            get {
                return ResourceManager.GetString("BUDGET_REC_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101104.
        /// </summary>
        public static string BUDGET_REC_DELETE {
            get {
                return ResourceManager.GetString("BUDGET_REC_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101105.
        /// </summary>
        public static string BUDGET_REC_EXPORT {
            get {
                return ResourceManager.GetString("BUDGET_REC_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101106.
        /// </summary>
        public static string BUDGET_REC_IMPORT {
            get {
                return ResourceManager.GetString("BUDGET_REC_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101101.
        /// </summary>
        public static string BUDGET_REC_READ {
            get {
                return ResourceManager.GetString("BUDGET_REC_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101103.
        /// </summary>
        public static string BUDGET_REC_UPDATE {
            get {
                return ResourceManager.GetString("BUDGET_REC_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101602.
        /// </summary>
        public static string BUDGET_REP_EXPORT {
            get {
                return ResourceManager.GetString("BUDGET_REP_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101603.
        /// </summary>
        public static string BUDGET_REP_PRINT {
            get {
                return ResourceManager.GetString("BUDGET_REP_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101601.
        /// </summary>
        public static string BUDGET_REP_READ {
            get {
                return ResourceManager.GetString("BUDGET_REP_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101202.
        /// </summary>
        public static string BUDGET_REV_ADD {
            get {
                return ResourceManager.GetString("BUDGET_REV_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101204.
        /// </summary>
        public static string BUDGET_REV_DELETE {
            get {
                return ResourceManager.GetString("BUDGET_REV_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101205.
        /// </summary>
        public static string BUDGET_REV_EXPORT {
            get {
                return ResourceManager.GetString("BUDGET_REV_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101206.
        /// </summary>
        public static string BUDGET_REV_IMPORT {
            get {
                return ResourceManager.GetString("BUDGET_REV_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101201.
        /// </summary>
        public static string BUDGET_REV_READ {
            get {
                return ResourceManager.GetString("BUDGET_REV_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101203.
        /// </summary>
        public static string BUDGET_REV_UPDATE {
            get {
                return ResourceManager.GetString("BUDGET_REV_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101403.
        /// </summary>
        public static string BUDGET_VIEW_EXPORT {
            get {
                return ResourceManager.GetString("BUDGET_VIEW_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101402.
        /// </summary>
        public static string BUDGET_VIEW_PRINT {
            get {
                return ResourceManager.GetString("BUDGET_VIEW_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101401.
        /// </summary>
        public static string BUDGET_VIEW_READ {
            get {
                return ResourceManager.GetString("BUDGET_VIEW_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100902.
        /// </summary>
        public static string CELLING_DEPT_ADD {
            get {
                return ResourceManager.GetString("CELLING_DEPT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100904.
        /// </summary>
        public static string CELLING_DEPT_DELETE {
            get {
                return ResourceManager.GetString("CELLING_DEPT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100901.
        /// </summary>
        public static string CELLING_DEPT_READ {
            get {
                return ResourceManager.GetString("CELLING_DEPT_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100903.
        /// </summary>
        public static string CELLING_DEPT_UPDATE {
            get {
                return ResourceManager.GetString("CELLING_DEPT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100802.
        /// </summary>
        public static string CELLING_HEAD_ADD {
            get {
                return ResourceManager.GetString("CELLING_HEAD_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100804.
        /// </summary>
        public static string CELLING_HEAD_DELETE {
            get {
                return ResourceManager.GetString("CELLING_HEAD_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100801.
        /// </summary>
        public static string CELLING_HEAD_READ {
            get {
                return ResourceManager.GetString("CELLING_HEAD_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100803.
        /// </summary>
        public static string CELLING_HEAD_UPDATE {
            get {
                return ResourceManager.GetString("CELLING_HEAD_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101002.
        /// </summary>
        public static string CELLING_SEC_ADD {
            get {
                return ResourceManager.GetString("CELLING_SEC_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101004.
        /// </summary>
        public static string CELLING_SEC_DELETE {
            get {
                return ResourceManager.GetString("CELLING_SEC_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101001.
        /// </summary>
        public static string CELLING_SEC_READ {
            get {
                return ResourceManager.GetString("CELLING_SEC_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101003.
        /// </summary>
        public static string CELLING_SEC_UPDATE {
            get {
                return ResourceManager.GetString("CELLING_SEC_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100502.
        /// </summary>
        public static string CONTROL_ADD {
            get {
                return ResourceManager.GetString("CONTROL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100504.
        /// </summary>
        public static string CONTROL_DELETE {
            get {
                return ResourceManager.GetString("CONTROL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100501.
        /// </summary>
        public static string CONTROL_READ {
            get {
                return ResourceManager.GetString("CONTROL_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100503.
        /// </summary>
        public static string CONTROL_UPDATE {
            get {
                return ResourceManager.GetString("CONTROL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101702.
        /// </summary>
        public static string CURRENCY_ADD {
            get {
                return ResourceManager.GetString("CURRENCY_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101704.
        /// </summary>
        public static string CURRENCY_DELETE {
            get {
                return ResourceManager.GetString("CURRENCY_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101701.
        /// </summary>
        public static string CURRENCY_READ {
            get {
                return ResourceManager.GetString("CURRENCY_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101703.
        /// </summary>
        public static string CURRENCY_UPDATE {
            get {
                return ResourceManager.GetString("CURRENCY_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100102.
        /// </summary>
        public static string DEPT_ADD {
            get {
                return ResourceManager.GetString("DEPT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100104.
        /// </summary>
        public static string DEPT_DELETE {
            get {
                return ResourceManager.GetString("DEPT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100101.
        /// </summary>
        public static string DEPT_READ {
            get {
                return ResourceManager.GetString("DEPT_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100103.
        /// </summary>
        public static string DEPT_UPDATE {
            get {
                return ResourceManager.GetString("DEPT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100702.
        /// </summary>
        public static string DETAIL_ADD {
            get {
                return ResourceManager.GetString("DETAIL_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100704.
        /// </summary>
        public static string DETAIL_DELETE {
            get {
                return ResourceManager.GetString("DETAIL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100701.
        /// </summary>
        public static string DETAIL_READ {
            get {
                return ResourceManager.GetString("DETAIL_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100703.
        /// </summary>
        public static string DETAIL_UPDATE {
            get {
                return ResourceManager.GetString("DETAIL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101802.
        /// </summary>
        public static string INFLATION_RATE_ADD {
            get {
                return ResourceManager.GetString("INFLATION_RATE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101804.
        /// </summary>
        public static string INFLATION_RATE_DELETE {
            get {
                return ResourceManager.GetString("INFLATION_RATE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101801.
        /// </summary>
        public static string INFLATION_RATE_READ {
            get {
                return ResourceManager.GetString("INFLATION_RATE_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101803.
        /// </summary>
        public static string INFLATION_RATE_UPDATE {
            get {
                return ResourceManager.GetString("INFLATION_RATE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000.
        /// </summary>
        public static string MTBF_ADMIN {
            get {
                return ResourceManager.GetString("MTBF_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100602.
        /// </summary>
        public static string REPORTIG_ADD {
            get {
                return ResourceManager.GetString("REPORTIG_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100604.
        /// </summary>
        public static string REPORTIG_DELETE {
            get {
                return ResourceManager.GetString("REPORTIG_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100601.
        /// </summary>
        public static string REPORTIG_READ {
            get {
                return ResourceManager.GetString("REPORTIG_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100603.
        /// </summary>
        public static string REPORTIG_UPDATE {
            get {
                return ResourceManager.GetString("REPORTIG_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100202.
        /// </summary>
        public static string SEC_ADD {
            get {
                return ResourceManager.GetString("SEC_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100204.
        /// </summary>
        public static string SEC_DELETE {
            get {
                return ResourceManager.GetString("SEC_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100201.
        /// </summary>
        public static string SEC_READ {
            get {
                return ResourceManager.GetString("SEC_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100203.
        /// </summary>
        public static string SEC_UPDATE {
            get {
                return ResourceManager.GetString("SEC_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100301.
        /// </summary>
        public static string TASK_ADD {
            get {
                return ResourceManager.GetString("TASK_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100304.
        /// </summary>
        public static string TASK_DELETE {
            get {
                return ResourceManager.GetString("TASK_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100302.
        /// </summary>
        public static string TASK_READ {
            get {
                return ResourceManager.GetString("TASK_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101902.
        /// </summary>
        public static string TASK_TYPE_ADD {
            get {
                return ResourceManager.GetString("TASK_TYPE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101904.
        /// </summary>
        public static string TASK_TYPE_DELETE {
            get {
                return ResourceManager.GetString("TASK_TYPE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101901.
        /// </summary>
        public static string TASK_TYPE_READ {
            get {
                return ResourceManager.GetString("TASK_TYPE_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101903.
        /// </summary>
        public static string TASK_TYPE_UPDATE {
            get {
                return ResourceManager.GetString("TASK_TYPE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100303.
        /// </summary>
        public static string TASK_UPDATE {
            get {
                return ResourceManager.GetString("TASK_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102002.
        /// </summary>
        public static string UOM_ADD {
            get {
                return ResourceManager.GetString("UOM_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102004.
        /// </summary>
        public static string UOM_DELETE {
            get {
                return ResourceManager.GetString("UOM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102001.
        /// </summary>
        public static string UOM_READ {
            get {
                return ResourceManager.GetString("UOM_READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 102003.
        /// </summary>
        public static string UOM_UPDATE {
            get {
                return ResourceManager.GetString("UOM_UPDATE", resourceCulture);
            }
        }
    }
}
